### ISSUE TITLE
Consider using a Open Source license

### ISSUE THREAD

**Issue by ghost** [44uk/nem2-faucet#4]
Hello @44uk!

I think the `nem2-facuet` is super useful, thanks for creating it! 😄 

One thing I miss is the license, without adding an explicit license, we are not able to fork it and modify it. Please, consider using some open source license (MIT, Apache-2.0, GPLv3, ...).

Thank you!

**Comment by 44uk** [comment]
Thank you for your pointing out. I totally forget it. I'll add license.

**Comment by 44uk** [comment]
Added.
